name = "hono-blog"
compatibility_date = "2024-11-06"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "todo"
database_id = "55673efc-c6de-4197-966c-345fb2a3ae86"